'use client'
import {useEffect,useState} from 'react'
import {adminFeatureListing,adminListListings,adminListPendingListings,adminUpdateListing,resetPassword,signIn,supabaseRequest} from '../../lib/supabase'

export default function AdminPage(){
 const [token,setToken]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[items,setItems]=useState<any[]>([]),[allListings,setAllListings]=useState<any[]>([]),[fees,setFees]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loginBusy,setLoginBusy]=useState(false),[resetBusy,setResetBusy]=useState(false),[resetSent,setResetSent]=useState(false)
 async function load(t:string){setError('');try{const [pending,all,feeResponse]=await Promise.all([adminListPendingListings(t),adminListListings(t),supabaseRequest('/rest/v1/marketplace_platform_fee_settings?select=fee_currency,fee_percent,enabled&order=fee_currency.asc',{},t)]);setItems(pending);setAllListings(all);if(!feeResponse.ok)throw new Error('Unable to load platform fees.');setFees(await feeResponse.json())}catch(e){setError(e instanceof Error?e.message:'Admin access required.')}}
 useEffect(()=>{const t=localStorage.getItem('gbk_marketplace_session')||'';if(t){setToken(t);load(t)}},[])
 async function login(e:React.FormEvent){e.preventDefault();setLoginBusy(true);setError('');try{const r=await signIn(email,password);const t=r?.access_token||'';if(!t)throw new Error('Sign in did not return an access token.');localStorage.setItem('gbk_marketplace_session',t);localStorage.setItem('gbk_marketplace_email',email);setToken(t);await load(t)}catch(e){setError(e instanceof Error?e.message:'Unable to sign in.')}finally{setLoginBusy(false)}}
 async function forgot(){if(!email.trim()){setError('Enter your admin email first.');return}setResetBusy(true);setError('');try{await resetPassword(email.trim());setResetSent(true)}catch(e){setError(e instanceof Error?e.message:'Unable to send reset email.')}finally{setResetBusy(false)}}
 async function change(id:string,status:string,verified=false){setBusy(id+status);setError('');try{await adminUpdateListing(id,status,verified,false,token);await load(token)}catch(e){setError(e instanceof Error?e.message:'Unable to update listing.')}finally{setBusy('')}}
 async function feature(id:string,value:boolean){setBusy('feature'+id);setError('');try{await adminFeatureListing(id,value,token);await load(token)}catch(e){setError(e instanceof Error?e.message:'Unable to update featured status.')}finally{setBusy('')}}
 async function saveFee(currency:string){const input=document.getElementById('fee-'+currency) as HTMLInputElement;const enabled=document.getElementById('enabled-'+currency) as HTMLInputElement;setBusy('fee'+currency);setError('');try{const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_update_fee',{method:'POST',body:JSON.stringify({p_currency:currency,p_fee_percent:Number(input.value),p_enabled:enabled.checked})},token);if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d?.message||'Unable to save fee.')}await load(token)}catch(e){setError(e instanceof Error?e.message:'Unable to save fee.')}finally{setBusy('')}}
 if(!token)return <main style={wrap}><header style={header}><a href="/">← GBK AI Marketplace</a></header><section style={card}><span style={eyebrow}>ADMIN</span><h1>Marketplace Admin</h1><p>Sign in with an authorized admin account to review listings and manage marketplace settings.</p><form onSubmit={login} style={form}><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" style={input}/><input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" style={input}/><button disabled={loginBusy||resetBusy} style={primary}>{loginBusy?'Signing in…':'Sign in →'}</button><button type="button" disabled={resetBusy||loginBusy} onClick={forgot} style={{...secondary,border:0,padding:0,textAlign:'left' as const}}>{resetBusy?'Sending reset email…':'Forgot password?'}</button>{resetSent&&<p>✓ Password reset email sent. Check your inbox.</p>}{error&&<p>{error}</p>}</form></section></main>
 return <main style={wrap}><header style={header}><a href="/">← Marketplace</a><strong>GBK AI Marketplace Admin</strong><a href="/dashboard">Business Dashboard</a></header><section style={{display:'grid',gap:24}}>{error&&<div style={notice}>{error}</div>}<section><span style={eyebrow}>ADMIN SETTINGS</span><h1>Marketplace Controls</h1><div style={card}><h2>Platform Fees</h2><p>Configure fees for local currency, USDT and GBK payments.</p><div style={{display:'grid',gap:12}}>{['LOCAL','USDT','GBK'].map(c=>{const f=fees.find(x=>x.fee_currency===c)||{fee_percent:5,enabled:true};return <div key={c} style={feeRow}><b>{c==='LOCAL'?'Local Currency':c}</b><input id={'fee-'+c} aria-label={c+' fee percentage'} type="number" min="0" max="100" step="0.01" defaultValue={f.fee_percent} style={smallInput}/><span>%</span><label><input id={'enabled-'+c} type="checkbox" defaultChecked={f.enabled}/> Enabled</label><button style={secondary} disabled={busy==='fee'+c} onClick={()=>saveFee(c)}>{busy==='fee'+c?'Saving…':'Save'}</button></div>})}</div></div></section>
<section><span style={eyebrow}>ADMIN APPROVAL</span><h1>Pending Listings</h1><p>Review submitted businesses before they become publicly discoverable.</p>{items.length===0?<div style={card}><h3>✓ No pending listings</h3><p>New business submissions will appear here.</p></div>:<div style={{display:'grid',gap:16}}>{items.map(x=><article key={x.id} style={card}><span style={pill}>{x.status}</span><h2>{x.business_name}</h2><h3>{x.title}</h3><p>{x.description||'No description provided.'}</p><p><b>Location:</b> {x.city||'—'}{x.country?', '+x.country:''}</p><p><b>Contact:</b> {x.email||x.phone||'—'}{x.website&&<> · <a href={x.website} target="_blank" rel="noreferrer">Website ↗</a></>}</p>{x.price_from!=null&&<p><b>From:</b> {x.currency||'USD'} {x.price_from}</p>}<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button disabled={!!busy} onClick={()=>change(x.id,'approved',true)} style={primary}>{busy===x.id+'approved'?'Approving…':'✓ Approve & Verify'}</button><button disabled={!!busy} onClick={()=>change(x.id,'approved',false)} style={secondary}>Approve</button><button disabled={!!busy} onClick={()=>change(x.id,'rejected')} style={secondary}>{busy===x.id+'rejected'?'Rejecting…':'Reject'}</button></div></article>)}</div>}</section>
<section><span style={eyebrow}>LISTING MANAGEMENT</span><h1>Approved & Featured</h1>{allListings.filter(x=>x.status==='approved').length===0?<div style={card}><p>No approved listings yet.</p></div>:<div style={{display:'grid',gap:12}}>{allListings.filter(x=>x.status==='approved').map(x=><div key={x.id} style={{...card,padding:18,display:'flex',justifyContent:'space-between',alignItems:'center',gap:14,flexWrap:'wrap'}}><div><b>{x.title}</b><div style={{color:'#71817b'}}>{x.business_name} • {x.city||x.country||'Global'} {x.verified?'• ✓ Verified':''}</div></div><button style={secondary} disabled={!!busy} onClick={()=>feature(x.id,!x.featured)}>{x.featured?'★ Featured — remove':'☆ Make featured'}</button></div>)}</div>}</section></section></main>
}
const wrap={maxWidth:1100,margin:'0 auto',padding:24,fontFamily:'Arial,sans-serif'}
const header={display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:36,flexWrap:'wrap' as const}
const card={padding:24,border:'1px solid #dbe8e3',borderRadius:20,background:'#fff'}
const eyebrow={letterSpacing:2,fontWeight:700}
const form={display:'grid',gap:14,maxWidth:480,marginTop:24}
const input={width:'100%',padding:14,border:'1px solid #ccdcd6',borderRadius:12,fontSize:16,boxSizing:'border-box' as const}
const smallInput={width:90,padding:10,border:'1px solid #ccdcd6',borderRadius:10,fontSize:15}
const feeRow={display:'flex',gap:10,alignItems:'center',flexWrap:'wrap' as const,padding:'12px 0',borderBottom:'1px solid #edf2f0'}
const primary={padding:'12px 16px',border:0,borderRadius:12,fontWeight:700,cursor:'pointer'}
const secondary={padding:'10px 14px',border:'1px solid #ccdcd6',borderRadius:12,background:'#fff',fontWeight:700,cursor:'pointer'}
const notice={padding:14,borderRadius:12,background:'#fff4f0',margin:'16px 0'}
const pill={display:'inline-block',padding:'5px 9px',borderRadius:99,background:'#fff3cd',fontSize:12,fontWeight:700,textTransform:'uppercase' as const}
