'use client'
import { useEffect, useState } from 'react'
import { createMarketplaceAIRequest, getMyMarketplaceAIRequests } from '../../lib/supabase'
export default function RequestsPage(){
 const [items,setItems]=useState<any[]>([])
 const [loading,setLoading]=useState(true)
 const [error,setError]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{const token=localStorage.getItem('gbk_marketplace_session')||'';if(!token){setError('Please sign in to view your requests.');setLoading(false);return}getMyMarketplaceAIRequests(token).then(setItems).catch(e=>setError(e instanceof Error?e.message:'Unable to load requests.')).finally(()=>setLoading(false))},[])
 return <main style={{minHeight:'100vh',background:'#edf4f1',padding:'24px 16px'}}><div style={{maxWidth:900,margin:'0 auto'}}><a href="/">← GBK AI Marketplace</a><h1 style={{marginTop:24}}>My GBK AI Requests</h1>{loading&&<p>Loading…</p>}{error&&<p>{error}</p>}{!loading&&!error&&!items.length&&<p>No requests yet. <a href="/">Ask GBK AI for anything.</a></p>}<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await createMarketplaceAIRequest({request_text:String(f.get('request_text')||''),category:String(f.get('category')||'GBK AI Marketplace'),language:String(f.get('language')||'en-US'),location_text:String(f.get('location_text')||''),contact_text:String(f.get('contact_text')||'')});setMessage('Requirement sent successfully.');e.currentTarget.reset();const token=localStorage.getItem('gbk_marketplace_session')||'';if(token)setItems(await getMyMarketplaceAIRequests(token))}catch(err){setMessage(err instanceof Error?err.message:'Unable to send requirement.')}}} style={{background:'#fff',borderRadius:16,padding:18,border:'1px solid #d7e4df',marginTop:18}}><h2>Ask GBK AI for anything</h2><p>Food, travel, cabs, shopping, services, property, shipping, learning, agriculture, spiritual needs, digital services and more.</p><textarea name="request_text" required minLength={3} rows={4} placeholder="What do you need?" style={{width:'100%',padding:12,borderRadius:12,border:'1px solid #d7e4df'}}/><div style={{display:'grid',gap:10,marginTop:10}}><input name="location_text" placeholder="Location / city / country" style={{padding:12,borderRadius:12,border:'1px solid #d7e4df'}}/><input name="contact_text" placeholder="Phone / WhatsApp / email (optional)" style={{padding:12,borderRadius:12,border:'1px solid #d7e4df'}}/></div><button className="primary" type="submit" style={{marginTop:12}}>Send requirement →</button>{message&&<p>{message}</p>}</form><div style={{display:'grid',gap:14}}>{items.map((x:any)=><article key={x.id} style={{background:'#fff',borderRadius:16,padding:18,border:'1px solid #d7e4df'}}><small>{x.category} · {x.status}</small><h3>{x.request_text}</h3><p>{x.location_text||'Location not specified'}</p></article>)}</div></div></main>
}