'use client'

import { useEffect, useMemo, useState } from 'react'
import InstallPWA from './InstallPWA'
import { aiMarketplaceSearch, getApprovedListings, signIn, signUp, submitListingRequest } from '../lib/supabase'

const categories=[{name:'Food & Restaurants',icon:'🍴',tag:'Food'},{name:'Travel & Tourism',icon:'🌍',tag:'Travel'},{name:'Real Estate',icon:'🏡',tag:'Property'},{name:'Local Services',icon:'🔧',tag:'Services'},{name:'Shopping',icon:'🛒',tag:'Shopping'},{name:'AI & Digital Services',icon:'✨',tag:'Digital'}]
const listings=[{icon:'🍽️',title:'Local Food & Dining',text:'Discover restaurants, cafes and food offers near you.',tag:'Food',keywords:'restaurant cafe food dining',id:undefined},{icon:'✈️',title:'Travel & Tourism',text:'Find stays, tours, experiences and travel services.',tag:'Travel',keywords:'hotel travel tours tourism',id:undefined},{icon:'🏠',title:'Real Estate',text:'Explore properties, plots and trusted local agents.',tag:'Property',keywords:'plots property house real estate',id:undefined},{icon:'🛠️',title:'Local Services',text:'Connect with service providers and professionals.',tag:'Services',keywords:'services repair professionals',id:undefined},{icon:'🛍️',title:'Shopping',text:'Discover local products, stores and special offers.',tag:'Shopping',keywords:'shopping stores products offers',id:undefined},{icon:'🤖',title:'AI & Digital Services',text:'Access AI tools, digital products and business services.',tag:'Digital',keywords:'ai tools digital software',id:undefined}]

export default function Home(){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[showBusiness,setShowBusiness]=useState(false),[showAuth,setShowAuth]=useState(false),[submitted,setSubmitted]=useState(false),[authMode,setAuthMode]=useState<'signin'|'signup'>('signin'),[authMessage,setAuthMessage]=useState(''),[liveListings,setLiveListings]=useState<any[]>([]),[userEmail,setUserEmail]=useState(''),[aiAnswer,setAiAnswer]=useState(''),[aiLoading,setAiLoading]=useState(false),[aiError,setAiError]=useState(''),[listening,setListening]=useState(false),[voiceError,setVoiceError]=useState(''),[speaking,setSpeaking]=useState(false)
 useEffect(()=>{getApprovedListings().then(setLiveListings).catch(()=>setLiveListings([]));setUserEmail(localStorage.getItem('gbk_marketplace_email')||'')},[])
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();const local=listings.filter(x=>(filter==='All'||x.tag===filter)&&(!q||`${x.title} ${x.text} ${x.keywords}`.toLowerCase().includes(q)));const real=liveListings.map(x=>({icon:'📍',title:x.title||x.business_name,text:x.description||`Discover ${x.business_name} in ${x.city||x.country||'your area'}.`,tag:x.marketplace_categories?.name||'Marketplace',keywords:`${x.business_name} ${x.title} ${x.city||''} ${x.country||''}`,id:x.id})).filter(x=>(filter==='All'||x.tag===filter||x.tag==='Marketplace')&&(!q||`${x.title} ${x.text} ${x.keywords}`.toLowerCase().includes(q)));return [...real,...local]},[query,filter,liveListings])
 const scrollToExplore=()=>document.getElementById('explore')?.scrollIntoView({behavior:'smooth'})
 async function runAiSearch(text=query){const q=text.trim();if(!q)return;setAiLoading(true);setAiError('');setAiAnswer('');setQuery(q);try{const [ai]=await Promise.all([fetch('/api/ai-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q})}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.error||'GBK AI search failed');return d.answer||''}),aiMarketplaceSearch(q).then(data=>{setLiveListings(Array.isArray(data)?data:[])}).catch(()=>[]) ]);setAiAnswer(ai)}catch(err){setAiError(err instanceof Error?err.message:'GBK AI search is unavailable right now.')}finally{setAiLoading(false);scrollToExplore()}}
 function startVoiceSearch(){setVoiceError('');const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){setVoiceError('Voice input is not supported in this browser. Try Chrome or Samsung Internet.');return}try{const recognition=new SR();recognition.lang='en-US';recognition.continuous=false;recognition.interimResults=false;recognition.maxAlternatives=1;recognition.onstart=()=>setListening(true);recognition.onresult=(event:any)=>{const text=event.results?.[0]?.[0]?.transcript||'';if(text)setQuery(text);if(text)runAiSearch(text)};recognition.onerror=(event:any)=>setVoiceError(event?.error==='not-allowed'?'Microphone permission was denied. Please allow microphone access for market.gbkai.com.':'Voice input could not start. Please try again.');recognition.onend=()=>setListening(false);recognition.start()}catch{setListening(false);setVoiceError('Voice input could not start. Please try again.')}}
 function speakAnswer(){if(!aiAnswer||typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(aiAnswer);utterance.lang='en-US';utterance.onstart=()=>setSpeaking(true);utterance.onend=()=>setSpeaking(false);utterance.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(utterance)}
 function stopSpeaking(){if(typeof window!=='undefined'&&'speechSynthesis' in window){window.speechSynthesis.cancel();setSpeaking(false)}}
 async function handleAuth(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setAuthMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')||''),password=String(f.get('password')||'');try{const data=authMode==='signin'?await signIn(email,password):await signUp(email,password);setUserEmail(data.user?.email||email);localStorage.setItem('gbk_marketplace_email',data.user?.email||email);if(data.access_token)localStorage.setItem('gbk_marketplace_session',data.access_token);setAuthMessage(authMode==='signup'&&!data.access_token?'Account created. Check your email if confirmation is enabled.':'Signed in successfully.')}catch(err){setAuthMessage(err instanceof Error?err.message:'Please try again.')}}
 async function handleBusiness(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await submitListingRequest({business_name:String(f.get('business_name')||''),category:String(f.get('category')||''),city_country:String(f.get('city_country')||''),contact:String(f.get('contact')||''),user_id:null});setSubmitted(true)}catch{setSubmitted(false);setAuthMessage('We could not submit the request right now. Please try again.')}}
 return <main><header className="nav"><a className="brand" href="/"><span className="logo">GBK</span><span>AI Marketplace</span></a><div className="links"><a href="#explore">Explore</a><a href="#categories">Categories</a><a href="#business">For Business</a>{userEmail&&<a href="/dashboard">Dashboard</a>}<button onClick={()=>{setAuthMessage('');setShowAuth(true)}}>{userEmail||'Sign in'}</button></div></header><InstallPWA />
 <section className="hero"><div className="hero-inner"><div className="eyebrow">GLOBAL MARKETPLACE • AI-FIRST</div><h1>Find what you need.<br/><em>Buy local. Go global.</em></h1><p>Discover stores, services, experiences and digital products — powered by GBK AI.</p><form className="search" onSubmit={e=>{e.preventDefault();runAiSearch()}}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask GBK AI what you need..." aria-label="AI marketplace search"/><button type="button" onClick={startVoiceSearch} aria-label="Speak your marketplace search" title="Speak" style={{minWidth:48,padding:'0 14px',fontSize:20}}>{listening?'🔴':'🎙️'}</button><button type="submit" disabled={aiLoading}>{aiLoading?'Thinking…':'Ask GBK AI'}</button></form>{voiceError&&<div className="result-count" style={{marginTop:10}}>{voiceError}</div>}<div className="quick"><span>Try:</span>{['Restaurants in Hyderabad','Hotels in Dubai','Plots under ₹50 lakh','AC repair service','AI tools'].map(x=><button key={x} onClick={()=>runAiSearch(x)}>{x}</button>)}</div></div></section>
 <section id="categories" className="section"><div className="section-head"><div><span className="eyebrow">EXPLORE</span><h2>Everything in one marketplace</h2></div><button className="text-button" onClick={scrollToExplore}>View all →</button></div><div className="categories">{categories.map(c=><button className="category" key={c.name} onClick={()=>{setFilter(c.tag);scrollToExplore()}}><span>{c.icon}</span><strong>{c.name}</strong><small>Explore →</small></button>)}</div></section>
 <section id="explore" className="section muted"><div className="section-head"><div><span className="eyebrow">GBK AI DISCOVERY</span><h2>Explore opportunities around you</h2><p className="result-count">{filtered.length} results available</p></div><div className="filters">{['All','Food','Travel','Property','Services','Shopping','Digital'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{aiAnswer&&<div className="ai-result"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><span className="eyebrow">GBK AI</span><div style={{display:'flex',gap:8}}><button type="button" onClick={speaking?stopSpeaking:speakAnswer} aria-label={speaking?'Stop reading':'Read answer aloud'} title={speaking?'Stop':'Read aloud'} style={{border:'1px solid #d7e4df',background:'#fff',borderRadius:12,padding:'8px 12px',cursor:'pointer',fontSize:18}}>{speaking?'🔇':'🔊'}</button></div></div><p>{aiAnswer}</p></div>}{aiError&&<div className="ai-result"><p>{aiError}</p></div>}<div className="cards">{filtered.map((x,i)=><article className="card" key={`${x.title}-${i}`}><div className="card-icon">{x.icon}</div><div className="tag">{x.tag}</div><h3>{x.title}</h3><p>{x.text}</p>{x.id?<a className="outline" href={`/listing?id=${x.id}`}>View details →</a>:<button className="outline" onClick={()=>{setQuery(x.tag);window.scrollTo({top:0,behavior:'smooth'})}}>Explore</button>}</article>)}</div>{filtered.length===0&&<div className="empty"><h3>No matching marketplace result</h3><p>Try another search or browse all categories.</p><button className="outline" onClick={()=>{setQuery('');setFilter('All');setAiAnswer('')}}>Show all</button></div>}</section>
 <section id="business" className="business"><div><span className="eyebrow">FOR BUSINESS</span><h2>Bring your business to the global marketplace.</h2><p>Create your listing, reach new customers and grow with AI-powered discovery.</p></div><button onClick={()=>{setSubmitted(false);setShowBusiness(true)}}>List your business →</button></section><footer><div className="brand"><span className="logo">GBK</span><span>AI Marketplace</span></div><div><a href="/privacy">Privacy</a> · <a href="/terms">Terms</a> · <a href="/dashboard">Dashboard</a></div></footer>
 {showBusiness&&<div className="modal-backdrop" onClick={()=>setShowBusiness(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowBusiness(false)}>×</button>{submitted?<div className="success"><div className="success-icon">✓</div><h2>Request received</h2><p>Your business listing request has been saved for marketplace review.</p><button className="primary" onClick={()=>setShowBusiness(false)}>Done</button></div>:<><span className="eyebrow">FOR BUSINESS</span><h2>List your business</h2><p className="modal-copy">Submit your business for review and publication.</p><form onSubmit={handleBusiness}><label>Business name<input name="business_name" required placeholder="Your business name"/></label><label>Category<select name="category" required defaultValue=""><option value="" disabled>Select category</option>{categories.map(c=><option key={c.name} value={c.tag}>{c.name}</option>)}</select></label><label>City / Country<input name="city_country" required placeholder="e.g. Hyderabad, India"/></label><label>Phone or email<input name="contact" required placeholder="Contact details"/></label><button className="primary" type="submit">Submit listing request</button></form></>}</div></div>}
 {showAuth&&<div className="modal-backdrop" onClick={()=>setShowAuth(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setShowAuth(false)}>×</button><span className="eyebrow">GBK AI ACCOUNT</span><h2>{authMode==='signin'?'Sign in':'Create account'}</h2><p className="modal-copy">Use your email to manage marketplace activity.</p><form onSubmit={handleAuth}><label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength={6} required placeholder="Minimum 6 characters"/></label><button className="primary" type="submit">{authMode==='signin'?'Sign in':'Create account'}</button></form>{authMessage&&<p className="result-count">{authMessage}</p>}<button className="text-button" onClick={()=>{setAuthMode(authMode==='signin'?'signup':'signin');setAuthMessage('')}}>{authMode==='signin'?'Create a new account':'Already have an account? Sign in'}</button></div></div>}</main>
}
