'use client'
import { useEffect, useState } from 'react'
import { addFavorite, createBooking, getApprovedListings, getListing, getListingPhotos, getListingReviews, removeFavorite, sendMarketplaceMessage, submitEnquiry, submitReview, tokenUserId } from '../../lib/supabase'

export default function ListingsPage(){
 const [items,setItems]=useState<any[]>([]),[q,setQ]=useState(''),[selected,setSelected]=useState<any>(null),[reviews,setReviews]=useState<any[]>([]),[photos,setPhotos]=useState<any[]>([]),[sent,setSent]=useState(false),[reviewSent,setReviewSent]=useState(false),[bookingSent,setBookingSent]=useState(false),[messageSent,setMessageSent]=useState(false),[favorite,setFavorite]=useState(false),[error,setError]=useState(''),[reviewError,setReviewError]=useState(''),[bookingError,setBookingError]=useState(''),[messageError,setMessageError]=useState('')
 useEffect(()=>{getApprovedListings().then(setItems).catch(()=>setItems([]));const id=new URLSearchParams(window.location.search).get('id');if(id)openListing(id)},[])
 async function openListing(id:string){const x=await getListing(id).catch(()=>null);setSelected(x);setSent(false);setReviewSent(false);setBookingSent(false);setMessageSent(false);setError('');setReviewError('');setBookingError('');setMessageError('');if(x){getListingReviews(id).then(setReviews).catch(()=>setReviews([]));getListingPhotos(id).then(setPhotos).catch(()=>setPhotos([]))}}
 const filtered=items.filter(x=>`${x.business_name||''} ${x.title||''} ${x.description||''} ${x.city||''} ${x.country||''} ${x.marketplace_categories?.name||''}`.toLowerCase().includes(q.toLowerCase()))
 async function enquiry(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget),token=localStorage.getItem('gbk_marketplace_session')||'';try{await submitEnquiry({listing_id:selected.id,user_id:token?tokenUserId(token):null,name:String(f.get('name')),contact:String(f.get('contact')),message:String(f.get('message'))},token||undefined);setSent(true)}catch(err){setError(err instanceof Error?err.message:'Unable to send enquiry')}}
 async function booking(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBookingError('');const token=localStorage.getItem('gbk_marketplace_session')||'',userId=token?tokenUserId(token):null;if(!token||!userId){setBookingError('Please sign in to request a booking.');return}const f=new FormData(e.currentTarget);try{await createBooking({listing_id:selected.id,user_id:userId,requested_date:String(f.get('date')),name:String(f.get('name')),contact:String(f.get('contact')),message:String(f.get('message')||''),status:'pending'},token);setBookingSent(true)}catch(err){setBookingError(err instanceof Error?err.message:'Unable to request booking')}}
 async function message(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setMessageError('');const token=localStorage.getItem('gbk_marketplace_session')||'',userId=token?tokenUserId(token):null;if(!token||!userId){setMessageError('Please sign in to message this business.');return}if(!selected?.owner_id){setMessageError('This business is not yet connected to messaging.');return}const f=new FormData(e.currentTarget);try{await sendMarketplaceMessage({listing_id:selected.id,sender_id:userId,recipient_id:selected.owner_id,message:String(f.get('message'))},token);setMessageSent(true)}catch(err){setMessageError(err instanceof Error?err.message:'Unable to send message')}}
 async function toggleFavorite(){const token=localStorage.getItem('gbk_marketplace_session')||'',userId=token?tokenUserId(token):null;if(!token||!userId){setError('Please sign in to save favorites.');return}try{if(favorite)await removeFavorite(selected.id,userId,token);else await addFavorite(selected.id,userId,token);setFavorite(!favorite)}catch(err){setError(err instanceof Error?err.message:'Unable to update favorite')}}
 async function review(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setReviewError('');const token=localStorage.getItem('gbk_marketplace_session')||'',userId=token?tokenUserId(token):null;if(!token||!userId){setReviewError('Please sign in to leave a review.');return}const f=new FormData(e.currentTarget);try{await submitReview({listing_id:selected.id,user_id:userId,rating:Number(f.get('rating')),review:String(f.get('review')||'')},token);setReviewSent(true);getListingReviews(selected.id).then(setReviews).catch(()=>{})}catch(err){setReviewError(err instanceof Error?err.message:'Unable to submit review')}}
 return <main style={{maxWidth:1100,margin:'0 auto',padding:24,fontFamily:'Arial,sans-serif'}}><header style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,marginBottom:40}}><a href="/">← GBK AI Marketplace</a><a href="/dashboard">Dashboard</a></header><span style={{letterSpacing:2,fontWeight:700}}>DISCOVER</span><h1>Marketplace listings</h1><p>Find approved businesses, products and services.</p><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search business, city or service…" style={{width:'100%',padding:16,borderRadius:14,border:'1px solid #ddd',margin:'20px 0 30px',fontSize:16}}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(260px,1fr))',gap:18}}>{filtered.map(x=><article key={x.id} style={{padding:22,border:'1px solid #ddd',borderRadius:20}}>{x.image_url?<img src={x.image_url} alt={x.business_name||x.title} loading="lazy" style={{width:"100%",height:170,objectFit:"cover",borderRadius:14,marginBottom:12}}/>:<div style={{height:170,borderRadius:14,background:"#eef4f1",display:"grid",placeItems:"center",fontSize:42,marginBottom:12}}>📷</div>}<small>{x.city}{x.country?`, ${x.country}`:''}</small><h2>{x.business_name||x.title}</h2><p>{x.description||'Marketplace listing'}</p>{x.verified&&<b>✓ Verified</b>}{x.price_from!=null&&<p>{x.currency||'USD'} {x.price_from}+</p>}<button onClick={()=>openListing(x.id)} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #aaa',background:'#fff'}}>View details →</button></article>)}</div>{filtered.length===0&&<p>No approved listings found yet. Businesses can submit a listing from the homepage.</p>}
 {selected&&<div onClick={()=>setSelected(null)} style={{position:'fixed',inset:0,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',padding:18,zIndex:20}}><div onClick={e=>e.stopPropagation()} style={{background:'#fff',borderRadius:24,padding:26,width:'min(720px,100%)',maxHeight:'90vh',overflow:'auto'}}><button onClick={()=>setSelected(null)} style={{float:'right',fontSize:24,border:0,background:'none'}}>×</button><small>{selected.city}{selected.country?`, ${selected.country}`:''}</small><h2>{selected.title}</h2><h3>{selected.business_name}</h3>{photos.length>0&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(130px,1fr))',gap:10,margin:'16px 0'}}>{photos.map((p:any)=><img key={p.id} src={p.image_url||p.url} alt={p.caption||selected.business_name} style={{width:'100%',height:130,objectFit:'cover',borderRadius:14}} loading="lazy"/> )}</div>}{selected.image_url&&photos.length===0&&<img src={selected.image_url} alt={selected.business_name} style={{width:'100%',maxHeight:280,objectFit:'cover',borderRadius:16,margin:'16px 0'}}/>}<p>{selected.description||'Marketplace listing'}</p>{selected.verified&&<p><b>✓ Verified listing</b></p>}{selected.address&&<p>📍 {selected.address}</p>}{selected.phone&&<p>☎ {selected.phone}</p>}{selected.email&&<p>✉ {selected.email}</p>}{selected.website&&<p><a href={selected.website} target="_blank" rel="noreferrer">Business website ↗</a></p>}{selected.price_from!=null&&<p><b>From {selected.currency||'USD'} {selected.price_from}</b></p>}{selected.price_from!=null&&<p><a href={`/checkout?id=${selected.id}`} style={{display:'inline-block',padding:'12px 18px',borderRadius:12,background:'#19745c',color:'#fff',fontWeight:700,textDecoration:'none'}}>🛒 Buy / Book & Pay →</a></p>}<button onClick={toggleFavorite} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #aaa',background:'#fff'}}>{favorite?'♥ Saved':'♡ Save favorite'}</button>{error&&<p>{error}</p>}
 <hr/><h3>📅 Request a booking</h3>{bookingSent?<p>✓ Booking request sent. The business can respond from the marketplace dashboard.</p>:<form onSubmit={booking} style={{display:'grid',gap:12}}><input name="name" required placeholder="Your name" style={{padding:12}}/><input name="contact" required placeholder="Phone or email" style={{padding:12}}/><input name="date" required type="date" style={{padding:12}}/><textarea name="message" placeholder="Service, quantity or special request" rows={3} style={{padding:12}}/><button type="submit" style={{padding:13,border:0,borderRadius:12}}>Request booking</button>{bookingError&&<small>{bookingError}</small>}</form>}
 <hr/><h3>💬 Message business</h3>{messageSent?<p>✓ Message sent. Check your Dashboard for replies.</p>:<form onSubmit={message} style={{display:'grid',gap:12}}><textarea name="message" required placeholder="Write your message to this business…" rows={4} style={{padding:12}}/><button type="submit" style={{padding:13,border:0,borderRadius:12}}>Send message</button>{messageError&&<small>{messageError}</small>}</form>}
 <hr/><h3>Send an enquiry</h3>{sent?<p>✓ Enquiry sent. The business can respond through the marketplace.</p>:<form onSubmit={enquiry} style={{display:'grid',gap:12}}><input name="name" required placeholder="Your name" style={{padding:12}}/><input name="contact" required placeholder="Phone or email" style={{padding:12}}/><textarea name="message" required placeholder="How can we help?" rows={4} style={{padding:12}}/><button type="submit" style={{padding:13,border:0,borderRadius:12}}>Send enquiry</button></form>}{error&&<small>{error}</small>}
 <hr/><h3>Reviews</h3>{reviews.length?reviews.map(r=><div key={r.id} style={{padding:'10px 0',borderBottom:'1px solid #eee'}}><b>{'★'.repeat(Math.max(0,Math.min(5,r.rating)))}</b><p>{r.review||'No written review.'}</p></div>):<p>No reviews yet.</p>}{reviewSent?<p>✓ Review submitted.</p>:<form onSubmit={review} style={{display:'grid',gap:12}}><select name="rating" defaultValue="5" style={{padding:12}}><option value="5">5 ★</option><option value="4">4 ★</option><option value="3">3 ★</option><option value="2">2 ★</option><option value="1">1 ★</option></select><textarea name="review" placeholder="Share your experience" rows={3} style={{padding:12}}/><button type="submit" style={{padding:13,border:0,borderRadius:12}}>Submit review</button>{reviewError&&<small>{reviewError}</small>}</form>}</div></div>}
 </main>
}
