const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://yjwgnapymqetxvksqacd.supabase.co'
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_Y3n5bVO3xveBnyt4LKbCPg_f5ilMSuz'
export async function supabaseRequest(path:string,options:RequestInit={},token?:string){const headers=new Headers(options.headers);headers.set('apikey',SUPABASE_KEY);headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);return fetch(`${SUPABASE_URL}${path}`,{...options,headers})}
async function readJson(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.msg||'Request failed');return d}
export async function submitListingRequest(data:any){const token=typeof window!=='undefined'?localStorage.getItem('gbk_marketplace_session')||'':'';const userId=token?tokenUserId(token):null;if(!token||!userId)throw new Error('Please sign in before creating a marketplace listing.');const categoryName=String(data?.category||'').trim();const categoryRows=await readJson(await supabaseRequest(`/rest/v1/marketplace_categories?select=id,name&name=eq.${encodeURIComponent(categoryName)}&limit=1`,{},token));const categoryId=categoryRows?.[0]?.id||null;const businessName=String(data?.business_name||'').trim();const location=String(data?.city_country||'').trim();const contact=String(data?.contact||'').trim();const email=/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact)?contact:null;const phone=email?null:contact;const title=String(data?.title||'').trim()||`${businessName} — ${categoryName}`;const description=String(data?.description||'').trim()||`${businessName} offers ${categoryName.toLowerCase()} products and services. Discover this business on GBK AI Marketplace.`;const parts=location.split(',').map((x:string)=>x.trim()).filter(Boolean);const city=parts[0]||null;const country=parts.length>1?parts.slice(1).join(', '):null;const payload={owner_id:userId,category_id:categoryId,business_name:businessName,title,description,city,country,phone,email,website:String(data?.website||'').trim()||null,price_from:data?.price_from??null,currency:String(data?.currency||'USD'),image_url:String(data?.image_url||'').trim()||null,status:'pending',featured:false,verified:false};return readJson(await supabaseRequest('/rest/v1/marketplace_listings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)},token)).then(rows=>rows?.[0]||rows)}
export async function signIn(email:string,password:string){return readJson(await supabaseRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})}))}
export async function signUp(email:string,password:string){return readJson(await supabaseRequest('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})}))}
export async function resetPassword(email:string){return readJson(await supabaseRequest('/auth/v1/recover',{method:'POST',body:JSON.stringify({email,redirect_to:'https://market.gbkai.com/reset-password'})}))}
export async function createMarketplaceAIRequest(data:any){
 const token=typeof window!=='undefined'?localStorage.getItem('gbk_marketplace_session')||'':'';
 const userId=token?tokenUserId(token):null;
 if(!token||!userId)throw new Error('Please sign in before sending a requirement.');
 const payload={customer_id:userId,request_text:String(data?.request_text||'').trim(),category:String(data?.category||'GBK AI Marketplace').trim()||'GBK AI Marketplace',language:String(data?.language||'en-US'),location_text:String(data?.location_text||'').trim()||null,contact_text:String(data?.contact_text||'').trim()||null,status:'open'};
 if(!payload.request_text)throw new Error('Please describe what you need.');
 return readJson(await supabaseRequest('/rest/v1/marketplace_ai_requests',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)},token)).then(rows=>rows?.[0]||rows)
}
export async function getMyMarketplaceAIRequests(token:string){
 return readJson(await supabaseRequest('/rest/v1/marketplace_ai_requests?select=*&order=created_at.desc',{},token))
}
export async function getApprovedListings(){return readJson(await supabaseRequest('/rest/v1/marketplace_listings?select=*,marketplace_categories(name,icon)&status=eq.approved&verified=eq.true&service_verified=eq.true&order=featured.desc,created_at.desc&limit=200'))}
export async function aiMarketplaceSearch(query:string){const all=await getApprovedListings();const q=query.trim().toLowerCase();if(!q)return all;const words=q.replace(/[^a-z0-9₹$€£]+/gi,' ').split(/\s+/).filter(w=>w.length>1);const categoryWords:any={restaurant:'Food',restaurants:'Food',food:'Food',cafe:'Food',cafes:'Food',dining:'Food',hotel:'Travel',hotels:'Travel',travel:'Travel',tour:'Travel',tours:'Travel',tourism:'Travel',holiday:'Travel',plot:'Property',plots:'Property',property:'Property',properties:'Property',real:'Property',estate:'Property',house:'Property',apartment:'Property',apartments:'Property',repair:'Services',service:'Services',services:'Services',ac:'Services',shopping:'Shopping',shop:'Shopping',store:'Shopping',stores:'Shopping',product:'Shopping',products:'Shopping',ai:'Digital',digital:'Digital',tools:'Digital',tool:'Digital'};const wantedCategories=new Set(words.map(w=>categoryWords[w]).filter(Boolean));return all.map((x:any)=>{const hay=`${x.business_name||''} ${x.title||''} ${x.description||''} ${x.city||''} ${x.country||''} ${x.marketplace_categories?.name||''}`.toLowerCase();const cat=String(x.marketplace_categories?.name||'').toLowerCase();const categoryMatch=[...wantedCategories].some((c:any)=>cat.includes(String(c).toLowerCase()))||wantedCategories.size===0;const wordMatch=words.some(w=>hay.includes(w));let score=(categoryMatch&&wantedCategories.size?10:0)+(wordMatch?3:0);if((x.city||'').toLowerCase().includes(q))score+=10;if((x.country||'').toLowerCase().includes(q))score+=8;return {x,score}}).filter((v:any)=>v.score>0).sort((a:any,b:any)=>b.score-a.score).slice(0,30).map((v:any)=>v.x)}
export async function getListing(id:string){const d=await readJson(await supabaseRequest(`/rest/v1/marketplace_listings?select=*,marketplace_categories(name,icon)&id=eq.${encodeURIComponent(id)}&limit=1`));return d[0]||null}
export async function getListingPhotos(listingId:string){return readJson(await supabaseRequest(`/rest/v1/marketplace_listing_photos?select=*&listing_id=eq.${encodeURIComponent(listingId)}&order=sort_order.asc,created_at.asc`))}
export async function addListingPhoto(data:any,token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_listing_photos',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)},token))}
export async function createBooking(data:any,token?:string){const r=await supabaseRequest('/rest/v1/marketplace_bookings',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(data)},token);return readJson(r)}
export async function updateBookingStatus(id:string,status:string,token:string){const r=await supabaseRequest(`/rest/v1/marketplace_bookings?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({status})},token);return readJson(r)}
export async function sendMarketplaceMessage(data:any,token?:string){const payload={listing_id:data?.listing_id,sender_user_id:data?.sender_user_id||data?.sender_id||null,sender_name:data?.sender_name||null,sender_contact:data?.sender_contact||null,recipient_user_id:data?.recipient_user_id||data?.recipient_id||null,message:String(data?.message||'')};const r=await supabaseRequest('/rest/v1/marketplace_messages',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(payload)},token);if(!r.ok)throw new Error('Unable to send message')}
export async function getMyBookings(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_bookings?select=*&order=created_at.desc',{},token))}
export async function getMyMessages(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_messages?select=*&order=created_at.desc',{},token))}
export async function getMyListings(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_listings?select=*&order=created_at.desc',{headers:{Prefer:'return=representation'}},token))}
export async function getMyListingRequests(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_listing_requests?select=*&order=created_at.desc',{},token))}
export async function getMyEnquiries(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_enquiries?select=*&order=created_at.desc',{},token))}
export async function getMyOrders(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_orders?select=*&order=created_at.desc',{},token))}
export async function getListingReviews(listingId:string){return readJson(await supabaseRequest(`/rest/v1/marketplace_reviews?select=*&listing_id=eq.${encodeURIComponent(listingId)}&order=created_at.desc`))}
export async function submitEnquiry(data:any,token?:string){const r=await supabaseRequest('/rest/v1/marketplace_enquiries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)},token);if(!r.ok)throw new Error('Unable to send enquiry')}
export async function submitReview(data:any,token:string){const r=await supabaseRequest('/rest/v1/marketplace_reviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)},token);if(!r.ok)throw new Error('Unable to submit review')}
export async function addFavorite(listingId:string,userId:string,token:string){const r=await supabaseRequest('/rest/v1/marketplace_favorites',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({listing_id:listingId,user_id:userId})},token);if(!r.ok&&r.status!==409)throw new Error('Unable to save favorite')}
export async function removeFavorite(listingId:string,userId:string,token:string){const r=await supabaseRequest(`/rest/v1/marketplace_favorites?listing_id=eq.${encodeURIComponent(listingId)}&user_id=eq.${encodeURIComponent(userId)}`,{method:'DELETE'},token);if(!r.ok)throw new Error('Unable to remove favorite')}
export function tokenUserId(token:string){try{const p=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return p.sub||null}catch{return null}}
export async function adminListPendingListings(token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_list_pending',{method:'POST',body:'{}'},token);return readJson(r)}
export async function adminUpdateListing(id:string,status:string,verified=false,featured=false,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_update_listing',{method:'POST',body:JSON.stringify({p_listing_id:id,p_status:status,p_verified:verified,p_featured:featured})},token);return readJson(r)}
export async function getPlatformFees(){return readJson(await supabaseRequest('/rest/v1/marketplace_platform_fee_settings?select=fee_currency,fee_percent,enabled&order=fee_currency.asc'))}
export async function createMarketplaceOrder(data:any,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_create_order',{method:'POST',body:JSON.stringify({p_listing_id:data.listing_id,p_amount:Number(data.amount),p_currency:String(data.currency||'USD'),p_payment_method:String(data.payment_method||'ONLINE'),p_customer_note:data.customer_note||null})},token);return readJson(r)}
export async function sellerUpdateOrderStatus(id:string,status:string,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_seller_update_order_status',{method:'POST',body:JSON.stringify({p_order_id:id,p_status:status})},token);return readJson(r)}
export async function adminFeatureListing(id:string,featured:boolean,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_feature_listing',{method:'POST',body:JSON.stringify({p_listing_id:id,p_featured:featured})},token);return readJson(r)}

export async function uploadMarketplacePhoto(file:File,listingId:string,token:string,userId:string){if(!token||!userId)throw new Error('Please sign in again before uploading a photo.');if(!file||!file.type.startsWith('image/'))throw new Error('Please select an image file.');if(file.size>8*1024*1024)throw new Error('Maximum photo size is 8 MB.');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=userId+'/'+listingId+'/'+crypto.randomUUID()+'.'+ext;const r=await fetch(SUPABASE_URL+'/storage/v1/object/marketplace-photos/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+token,'x-upsert':'false','cache-control':'3600','Content-Type':file.type},body:file});if(!r.ok){const raw=await r.text().catch(()=> '');let msg='Unable to upload photo.';try{const d=JSON.parse(raw);msg=d?.message||d?.error_description||d?.error||msg}catch{}if(r.status===401||r.status===403)msg='Photo upload is not authorized. Please sign in again.';throw new Error(msg)}const url=SUPABASE_URL+'/storage/v1/object/public/marketplace-photos/'+path;return addListingPhoto({listing_id:listingId,image_url:url,caption:'Business photo',sort_order:0},token)}

export async function adminListListings(token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_list_listings',{method:'POST',body:'{}'},token);return readJson(r)}

export async function createMatchedMarketplaceLeads(data:any,token:string){
 const r=await supabaseRequest('/rest/v1/rpc/marketplace_create_matched_leads',{method:'POST',body:JSON.stringify({p_request_text:String(data?.request_text||'').trim(),p_category:String(data?.category||'').trim(),p_city:String(data?.city||'').trim()||null,p_limit:Number(data?.limit||5)})},token);
 return readJson(r);
}

export async function createMarketplaceLead(listingId:string,requestText:string,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_create_lead',{method:'POST',body:JSON.stringify({p_listing_id:listingId,p_request_text:requestText})},token);return readJson(r)}
export async function ownerUpdateLeadStatus(leadId:string,status:'accepted'|'quoted'|'contacted'|'completed'|'declined',token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_owner_update_lead',{method:'POST',body:JSON.stringify({p_lead_id:leadId,p_status:status})},token);return readJson(r)}
export async function setLeadMatching(listingId:string,enabled:boolean,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_owner_set_lead_matching',{method:'POST',body:JSON.stringify({p_listing_id:listingId,p_enabled:enabled})},token);return readJson(r)}
export async function adminUpdateServiceVerification(id:string,verified:boolean,serviceVerified:boolean,leadMatching:boolean,token:string){const r=await supabaseRequest('/rest/v1/rpc/marketplace_admin_update_service_verification',{method:'POST',body:JSON.stringify({p_listing_id:id,p_verified:verified,p_service_verified:serviceVerified,p_lead_matching_enabled:leadMatching})},token);return readJson(r)}

export async function getMyLeads(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_leads?select=*,marketplace_listings(business_name,title,city,country)&order=created_at.desc',{},token))}

export async function searchCabOwners(city:string|null,lat?:number|null,lng?:number|null){const body={p_city:city,p_lat:lat??null,p_lng:lng??null,p_limit:20};return readJson(await supabaseRequest('/rest/v1/rpc/marketplace_cab_search',{method:'POST',body:JSON.stringify(body)}))}
export async function requestCabLead(cabOwnerId:string,pickup:string,destination:string){const token=typeof window!=='undefined'?localStorage.getItem('gbk_marketplace_session')||'':'';if(!token)throw new Error('Please sign in before requesting a cab.');return readJson(await supabaseRequest('/rest/v1/rpc/marketplace_cab_request_lead',{method:'POST',body:JSON.stringify({p_cab_owner_id:cabOwnerId,p_pickup:pickup,p_destination:destination})},token))}

export async function submitCabOwnerApplication(data:any){const token=typeof window!=='undefined'?localStorage.getItem('gbk_marketplace_session')||'':'';const userId=token?tokenUserId(token):null;if(!token||!userId)throw new Error('Please sign in before registering as a cab owner.');const payload={owner_id:userId,driver_name:String(data.driver_name||''),business_name:String(data.business_name||data.driver_name||''),phone:String(data.phone||''),email:String(data.email||''),emergency_contact:String(data.emergency_contact||''),city:String(data.city||''),country:String(data.country||'India'),vehicle_type:String(data.vehicle_type||''),vehicle_category:String(data.vehicle_category||'Cab'),vehicle_model:String(data.vehicle_model||''),vehicle_number:String(data.vehicle_number||''),registration_no:String(data.registration_no||''),driving_license_no:String(data.driving_license_no||''),driving_license_url:String(data.driving_license_url||''),registration_url:String(data.registration_url||''),insurance_policy_no:String(data.insurance_policy_no||''),insurance_url:String(data.insurance_url||''),pollution_certificate_no:String(data.pollution_certificate_no||''),pollution_url:String(data.pollution_url||''),seating_capacity:Number(data.seating_capacity||4),active:false,verified:false,verification_status:'pending'};return readJson(await supabaseRequest('/rest/v1/marketplace_cab_owners',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(payload)},token)).then(rows=>rows?.[0]||rows)}

export async function getMyCabOwner(token:string,userId:string){return readJson(await supabaseRequest('/rest/v1/marketplace_cab_owners?select=*&owner_id=eq.'+encodeURIComponent(userId)+'&order=created_at.desc&limit=1',{},token)).then((rows:any[])=>rows?.[0]||null)}
export async function getMyCabLeads(token:string,cabOwnerId:string){return readJson(await supabaseRequest('/rest/v1/marketplace_cab_leads?select=*&cab_owner_id=eq.'+encodeURIComponent(cabOwnerId)+'&order=created_at.desc',{},token))}
export async function updateCabOwnerStatus(token:string,cabOwnerId:string,active:boolean){return readJson(await supabaseRequest('/rest/v1/marketplace_cab_owners?id=eq.'+encodeURIComponent(cabOwnerId),{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({active})},token))}
export async function updateCabLeadStatus(token:string,leadId:string,status:'accepted'|'declined'|'completed'){return readJson(await supabaseRequest('/rest/v1/rpc/marketplace_cab_owner_update_lead',{method:'POST',body:JSON.stringify({p_lead_id:leadId,p_status:status})},token))}
