const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || 'https://yjwgnapymqetxvksqacd.supabase.co'
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || 'sb_publishable_Y3n5bVO3xveBnyt4LKbCPg_f5ilMSuz'
export async function supabaseRequest(path:string,options:RequestInit={},token?:string){const headers=new Headers(options.headers);headers.set('apikey',SUPABASE_KEY);headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);return fetch(`${SUPABASE_URL}${path}`,{...options,headers})}
async function readJson(r:Response){const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.message||d?.error_description||d?.msg||'Request failed');return d}
export async function submitListingRequest(data:any){const r=await supabaseRequest('/rest/v1/marketplace_listing_requests',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});if(!r.ok)throw new Error('Unable to submit listing request')}
export async function signIn(email:string,password:string){return readJson(await supabaseRequest('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})}))}
export async function signUp(email:string,password:string){return readJson(await supabaseRequest('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})}))}
export async function getApprovedListings(){return readJson(await supabaseRequest('/rest/v1/marketplace_listings?select=*,marketplace_categories(name,icon)&status=eq.approved&order=featured.desc,created_at.desc&limit=200'))}
export async function aiMarketplaceSearch(query:string){const all=await getApprovedListings();const q=query.trim().toLowerCase();if(!q)return all;const words=q.replace(/[^a-z0-9₹$€£]+/gi,' ').split(/\s+/).filter(w=>w.length>1);const categoryWords:any={restaurant:'Food',restaurants:'Food',food:'Food',cafe:'Food',cafes:'Food',dining:'Food',hotel:'Travel',hotels:'Travel',travel:'Travel',tour:'Travel',tours:'Travel',tourism:'Travel',holiday:'Travel',plot:'Property',plots:'Property',property:'Property',properties:'Property',real:'Property',estate:'Property',house:'Property',apartment:'Property',apartments:'Property',repair:'Services',service:'Services',services:'Services',ac:'Services',shopping:'Shopping',shop:'Shopping',store:'Shopping',stores:'Shopping',product:'Shopping',products:'Shopping',ai:'Digital',digital:'Digital',tools:'Digital',tool:'Digital'};const wantedCategories=new Set(words.map(w=>categoryWords[w]).filter(Boolean));return all.map((x:any)=>{const hay=`${x.business_name||''} ${x.title||''} ${x.description||''} ${x.city||''} ${x.country||''} ${x.marketplace_categories?.name||''}`.toLowerCase();const cat=String(x.marketplace_categories?.name||'').toLowerCase();const categoryMatch=[...wantedCategories].some((c:any)=>cat.includes(String(c).toLowerCase()))||wantedCategories.size===0;const wordMatch=words.some(w=>hay.includes(w));let score=(categoryMatch&&wantedCategories.size?10:0)+(wordMatch?3:0);if((x.city||'').toLowerCase().includes(q))score+=10;if((x.country||'').toLowerCase().includes(q))score+=8;return {x,score}}).filter((v:any)=>v.score>0).sort((a:any,b:any)=>b.score-a.score).slice(0,30).map((v:any)=>v.x)}
export async function getListing(id:string){const d=await readJson(await supabaseRequest(`/rest/v1/marketplace_listings?select=*,marketplace_categories(name,icon)&id=eq.${encodeURIComponent(id)}&limit=1`));return d[0]||null}
export async function getMyListings(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_listings?select=*&order=created_at.desc',{headers:{Prefer:'return=representation'}},token))}
export async function getMyListingRequests(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_listing_requests?select=*&order=created_at.desc',{},token))}
export async function getMyEnquiries(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_enquiries?select=*&order=created_at.desc',{},token))}
export async function getMyOrders(token:string){return readJson(await supabaseRequest('/rest/v1/marketplace_orders?select=*&order=created_at.desc',{},token))}
export async function getListingReviews(listingId:string){return readJson(await supabaseRequest(`/rest/v1/marketplace_reviews?select=*&listing_id=eq.${encodeURIComponent(listingId)}&order=created_at.desc`))}
export async function submitEnquiry(data:any,token?:string){const r=await supabaseRequest('/rest/v1/marketplace_enquiries',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)},token);if(!r.ok)throw new Error('Unable to send enquiry')}
export async function submitReview(data:any,token:string){const r=await supabaseRequest('/rest/v1/marketplace_reviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)},token);if(!r.ok)throw new Error('Unable to submit review')}
export async function addFavorite(listingId:string,userId:string,token:string){const r=await supabaseRequest('/rest/v1/marketplace_favorites',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({listing_id:listingId,user_id:userId})},token);if(!r.ok&&r.status!==409)throw new Error('Unable to save favorite')}
export async function removeFavorite(listingId:string,userId:string,token:string){const r=await supabaseRequest(`/rest/v1/marketplace_favorites?listing_id=eq.${encodeURIComponent(listingId)}&user_id=eq.${encodeURIComponent(userId)}`,{method:'DELETE'},token);if(!r.ok)throw new Error('Unable to remove favorite')}
export function tokenUserId(token:string){try{const p=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return p.sub||null}catch{return null}}
