'use client'
import {useEffect,useState} from 'react'
import {createMarketplaceOrder,getListing,getPlatformFees,tokenUserId} from '../../lib/supabase'

export default function Checkout(){
 const [listing,setListing]=useState<any>(null),[amount,setAmount]=useState(''),[currency,setCurrency]=useState('USD'),[method,setMethod]=useState('ONLINE'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[fee,setFee]=useState(5)
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get('id')||'';if(id)getListing(id).then(setListing).catch(()=>{});getPlatformFees().then((rows:any[])=>{const f=rows?.find(x=>x.fee_currency==='LOCAL');if(f)setFee(Number(f.fee_percent))}).catch(()=>{})},[])
 const base=Number(amount)||0,total=base+Math.round(base*fee)/100
 async function submit(e:React.FormEvent){e.preventDefault();const token=localStorage.getItem('gbk_marketplace_session')||'';if(!token||!tokenUserId(token)){setMessage('Please sign in before checkout.');return}if(!listing){setMessage('Listing not found.');return}setBusy(true);setMessage('');try{const o=await createMarketplaceOrder({listing_id:listing.id,amount:base,currency,payment_method:method,customer_note:note},token);setMessage('✓ Order created. Payment is ready for provider checkout. Order ID: '+(o?.id||'created'))}catch(err){setMessage(err instanceof Error?err.message:'Unable to create order.')}finally{setBusy(false)}}
 return <main style={{maxWidth:800,margin:'0 auto',padding:24,fontFamily:'Arial,sans-serif'}}><header style={{display:'flex',justifyContent:'space-between',marginBottom:35}}><a href="/">← Marketplace</a><a href="/dashboard">Dashboard</a></header>{!listing?<p>Loading checkout…</p>:<><span style={{letterSpacing:2,fontWeight:700}}>SECURE CHECKOUT</span><h1>{listing.title}</h1><p>{listing.business_name} • {listing.city||listing.country||'Global'}</p><form onSubmit={submit} style={{display:'grid',gap:16,marginTop:28,padding:24,border:'1px solid #dbe8e3',borderRadius:20,background:'#fff'}}><label>Amount<input required min="0.01" step="0.01" type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={listing.price_from?String(listing.price_from):'Enter amount'} style={input}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)} style={input}>{['USD','EUR','GBP','AED','SGD','AUD','CAD','INR','USDT','GBK'].map(x=><option key={x}>{x}</option>)}</select></label><label>Payment method<select value={method} onChange={e=>setMethod(e.target.value)} style={input}><option value="ONLINE">Online payment</option><option value="USDT">USDT</option><option value="GBK">GBK</option><option value="BANK">Bank transfer</option></select></label><label>Order note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Quantity, delivery or service details" style={input}/></label><div style={{padding:16,borderRadius:14,background:'#eef7f3'}}><b>Order summary</b><p style={{marginBottom:5}}>Item: {base.toFixed(2)} {currency}</p><p style={{margin:'5px 0'}}>Platform fee: {(base*fee/100).toFixed(2)} {currency}</p><strong>Total: {total.toFixed(2)} {currency}</strong></div><button disabled={busy} style={primary}>{busy?'Creating order…':'Continue to payment →'}</button>{message&&<div style={{padding:14,borderRadius:12,background:'#f2f7f5'}}>{message}</div>}</form><p style={{color:'#71817b',marginTop:16}}>Payment gateway and seller payout are provider-dependent; this checkout records the order and platform fee before gateway integration.</p></>}</main>
}
const input={width:'100%',padding:14,marginTop:7,border:'1px solid #ccdcd6',borderRadius:12,fontSize:16,boxSizing:'border-box' as const}
const primary={padding:14,border:0,borderRadius:12,fontWeight:700,cursor:'pointer'}
