'use client'
import { useEffect, useState } from 'react'
import { addListingPhoto,uploadMarketplacePhoto,getMyEnquiries,getMyListingRequests,getMyOrders,getMyListings,getMyBookings,getMyMessages,getMyLeads,sendMarketplaceMessage,updateBookingStatus,sellerUpdateOrderStatus,setLeadMatching } from '../../lib/supabase'

export default function Dashboard(){
 const [email,setEmail]=useState(''),[token,setToken]=useState(''),[data,setData]=useState<any>({listings:[],requests:[],enquiries:[],orders:[],bookings:[],messages:[]}),[message,setMessage]=useState(''),[busy,setBusy]=useState(''),[photoUrl,setPhotoUrl]=useState<Record<string,string>>({}),[photoMsg,setPhotoMsg]=useState<Record<string,string>>({}),[reply,setReply]=useState<Record<string,string>>({})
 const uid=()=>tokenUserId(token)
 async function load(t:string){const [listings,requests,enquiries,orders,bookings,messages,leads]=await Promise.all([getMyListings(t),getMyListingRequests(t),getMyEnquiries(t),getMyOrders(t),getMyBookings(t),getMyMessages(t),getMyLeads(t).catch(()=>[])]);setData({listings,requests,enquiries,orders,bookings,messages,leads})}
 useEffect(()=>{const t=localStorage.getItem('gbk_marketplace_session')||'';setToken(t);setEmail(localStorage.getItem('gbk_marketplace_email')||'');if(!t){setMessage('Please sign in from the marketplace home page first.');return}load(t).catch(()=>setMessage('Dashboard data could not be loaded. Please sign in again.'))},[])
 async function addPhoto(id:string){const url=(photoUrl[id]||'').trim();if(!url){setPhotoMsg(v=>({...v,[id]:'Enter a public image URL.'}));return}setBusy('photo'+id);try{await addListingPhoto({listing_id:id,image_url:url,caption:'Business photo',sort_order:0},token);setPhotoUrl(v=>({...v,[id]:''}));setPhotoMsg(v=>({...v,[id]:'✓ Photo added.'}))}catch(e){setPhotoMsg(v=>({...v,[id]:e instanceof Error?e.message:'Unable to add photo.'}))}finally{setBusy('')}}
 async function toggleLead(id:string,value:boolean){setBusy('lead'+id);try{await setLeadMatching(id,value,token);await load(token)}catch(e){setMessage(e instanceof Error?e.message:'Unable to update AI lead matching.')}finally{setBusy('')}}
 async function orderStatus(id:string,status:string){setBusy('order'+id);try{await sellerUpdateOrderStatus(id,status,token);await load(token)}catch(e){setMessage(e instanceof Error?e.message:'Unable to update order.')}finally{setBusy('')}}
 async function bookingStatus(id:string,status:string){setBusy('book'+id);try{await updateBookingStatus(id,status,token);await load(token)}catch(e){setMessage(e instanceof Error?e.message:'Unable to update booking.')}finally{setBusy('')}}
 async function sendReply(x:any){const text=(reply[x.id]||'').trim();if(!text)return;setBusy('msg'+x.id);try{await sendMarketplaceMessage({listing_id:x.listing_id,sender_user_id:uid(),recipient_user_id:x.sender_user_id,message:text},token);setReply(v=>({...v,[x.id]:''}));await load(token)}catch(e){setMessage(e instanceof Error?e.message:'Unable to send reply.')}finally{setBusy('')}}
 const revenue=data.orders.reduce((s:number,x:any)=>s+Number(x.amount||0),0),confirmed=data.bookings.filter((x:any)=>x.status==='confirmed').length,completed=data.bookings.filter((x:any)=>x.status==='completed').length
 return <main className="dashboard-page"><header className="nav"><a className="brand" href="/"><span className="logo">GBK</span><span>AI Marketplace</span></a><div style={{display:'flex',gap:12,alignItems:'center'}}><a className="primary inline-button" href="/business">+ Create listing</a><a className="text-button" href="/">← Marketplace</a></div></header><section className="section"><span className="eyebrow">ACCOUNT DASHBOARD</span><h1>Welcome{email?`, ${email}`:''}</h1><p>Manage listings, photos, leads, bookings, messages, orders and performance.</p>{message&&<div className="empty"><h3>{message}</h3></div>}
 <div className="dashboard-grid"><div className="dashboard-card"><span>🏪</span><strong>{data.listings.length}</strong><small>My listings</small></div><div className="dashboard-card"><span>📨</span><strong>{data.enquiries.length}</strong><small>Enquiries</small></div><div className="dashboard-card"><span>📅</span><strong>{data.bookings.length}</strong><small>Bookings</small></div><div className="dashboard-card"><span>💬</span><strong>{data.messages.length}</strong><small>Messages</small></div><div className="dashboard-card"><span>🧾</span><strong>{data.orders.length}</strong><small>Orders</small></div><div className="dashboard-card"><span>⏳</span><strong>{data.requests.length}</strong><small>Requests</small></div></div>
 <div className="dashboard-list"><h2>📊 Business Performance</h2><div className="dashboard-grid" style={{margin:'16px 0 0',gridTemplateColumns:'repeat(4,1fr)'}}><div className="dashboard-card"><strong>{data.listings.filter((x:any)=>x.status==='approved').length}</strong><small>Approved listings</small></div><div className="dashboard-card"><strong>{confirmed}</strong><small>Confirmed bookings</small></div><div className="dashboard-card"><strong>{completed}</strong><small>Completed bookings</small></div><div className="dashboard-card"><strong>{revenue.toFixed(2)}</strong><small>Order value</small></div></div><p style={{color:'#71817b'}}>Use enquiries, bookings and orders as your customer activity pipeline. Payment checkout can be connected to the order flow when the payment provider is configured.</p></div>
 <div className="dashboard-list"><h2>📸 My Listings & Photos</h2>{data.listings.length?data.listings.map((x:any)=><div className="row" key={x.id}><div style={{flex:1}}><strong>{x.title}</strong><small>{x.business_name} • {x.city||x.country||'Global'} • {x.status} {x.verified&&x.service_verified?'• ✓ Verified Service':''}</small><div style={{display:'flex',gap:8,marginTop:8,alignItems:'center'}}>{x.verified&&x.service_verified?<><span className="status">✓ Verified Service</span><button onClick={()=>toggleLead(x.id,!x.lead_matching_enabled)} disabled={busy==='lead'+x.id} style={{padding:'7px 10px',borderRadius:9,border:'1px solid #ccdcd6',background:'#fff'}}>{x.lead_matching_enabled?'🤖 AI Leads ON':'🤖 Turn AI Leads ON'}</button>{x.lead_matching_enabled&&<small>Free accepted leads used: {Math.min(Number(x.lead_free_used||0),5)}/5</small>}</>:<small>Verification required before AI lead matching.</small>}</div><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><input value={photoUrl[x.id]||''} onChange={e=>setPhotoUrl(v=>({...v,[x.id]:e.target.value}))} placeholder="Paste business photo URL" style={{flex:'1 1 260px',padding:10,border:'1px solid #ccdcd6',borderRadius:10}}/><button disabled={busy==='photo'+x.id} onClick={()=>addPhoto(x.id)} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #ccdcd6',background:'#fff',fontWeight:700}}>{busy==='photo'+x.id?'Adding…':'📸 Add photo'}</button><input type="file" accept="image/*" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const uid=tokenUserId(token);setBusy("upload"+x.id);try{if(file.size>8*1024*1024)throw new Error("Maximum photo size is 8 MB.");await uploadMarketplacePhoto(file,x.id,token,uid);setPhotoMsg(v=>({...v,[x.id]:"✓ Photo uploaded."}));await load(token)}catch(err){setPhotoMsg(v=>({...v,[x.id]:err instanceof Error?err.message:"Unable to upload photo."}))}finally{setBusy("")}}} style={{flex:"1 1 220px"}}/></div>{photoMsg[x.id]&&<small>{photoMsg[x.id]}</small>}</div><span className="status">{x.status}</span></div>):<p>No listings yet. <a href="/business">Create your first listing →</a></p>}</div>
 <div className="dashboard-list"><h2>📅 Booking Management</h2>{data.bookings.length?data.bookings.map((x:any)=><div className="row" key={x.id}><div><strong>{x.name}</strong><small>{x.requested_date||'Flexible date'} {x.requested_time?`• ${x.requested_time}`:''} • {x.message||'Booking request'}</small><div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}>{['confirmed','completed','cancelled'].map(s=><button key={s} disabled={busy==='book'+x.id} onClick={()=>bookingStatus(x.id,s)} style={{padding:'7px 10px',borderRadius:9,border:'1px solid #ccdcd6',background:'#fff'}}>{s}</button>)}</div></div><span className="status">{x.status}</span></div>):<p>No booking requests yet.</p>}</div>
 <div className="dashboard-list"><h2>💬 Message Inbox</h2>{data.messages.length?data.messages.map((x:any)=>{const mine=x.sender_user_id===uid();return <div className="row" key={x.id}><div style={{flex:1}}><strong>{mine?'You':(x.sender_name||'Customer')}</strong><small>{x.message}</small>{!mine&&<div style={{display:'flex',gap:8,marginTop:8}}><input value={reply[x.id]||''} onChange={e=>setReply(v=>({...v,[x.id]:e.target.value}))} placeholder="Write a reply…" style={{flex:1,padding:10,border:'1px solid #ccdcd6',borderRadius:10}}/><button disabled={busy==='msg'+x.id} onClick={()=>sendReply(x)} style={{padding:'10px 14px',borderRadius:10,border:'1px solid #ccdcd6',background:'#fff',fontWeight:700}}>{busy==='msg'+x.id?'Sending…':'Reply'}</button></div>}</div><span className="status">{mine?'sent':'received'}</span></div>}):<p>No messages yet.</p>}</div>
 <div className="dashboard-list"><h2>🤖 AI Lead Inbox</h2>{data.leads.length?data.leads.map((x:any)=><div className="row" key={x.id}><div><strong>{x.marketplace_listings?.business_name||'Business lead'}</strong><small>{x.request_text}</small><small>{x.is_free?'🎁 Free lead':'Lead'} • {new Date(x.created_at).toLocaleString()}</small></div><span className="status">{x.status}</span></div>):<p>No AI leads yet. Turn on AI Leads for a verified service.</p>}</div><div className="dashboard-list"><h2>Listing Requests</h2>{data.requests.length?data.requests.map((x:any)=><div className="row" key={x.id}><div><strong>{x.business_name}</strong><small>{x.category} • {x.city_country}</small></div><span className="status">{x.status}</span></div>):<p>No listing requests yet.</p>}</div><div className="dashboard-list"><h2>My Enquiries</h2>{data.enquiries.length?data.enquiries.map((x:any)=><div className="row" key={x.id}><div><strong>{x.name}</strong><small>{x.message}</small></div><span className="status">{x.status}</span></div>):<p>No enquiries yet.</p>}</div><div className="dashboard-list"><h2>Orders & Payments</h2>{data.orders.length?data.orders.map((x:any)=><div className="row" key={x.id}><div style={{flex:1}}><strong>{x.item_title||'Marketplace order'}</strong><small>{x.currency} {x.amount} • Platform fee {x.platform_fee||0} {x.currency} • {new Date(x.created_at).toLocaleString()}</small><small>Payment: {x.payment_status||'unpaid'} • Seller receives: {x.seller_amount||0} {x.currency}</small>{x.seller_id===uid()&&<div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}>{['confirmed','completed','cancelled'].map(s=><button key={s} disabled={busy==='order'+x.id} onClick={()=>orderStatus(x.id,s)} style={{padding:'7px 10px',borderRadius:9,border:'1px solid #ccdcd6',background:'#fff'}}>{s}</button>)}</div>}</div><span className="status">{x.status}</span></div>):<p>No orders yet.</p>}<p style={{color:'#71817b'}}>Orders are recorded with platform fees and payment status. Online gateway settlement remains provider-dependent until a payment provider is connected.</p></div></section></main>
}
function tokenUserId(token:string){try{const p=JSON.parse(atob(token.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));return p.sub||null}catch{return null}}
